### PR TITLE
Support for 1.18.

### PR DESCRIPTION
**Pull request by SzczurekYT**
Hello
Thanks for the mod.
Currently many server's are still on 1.18, so I decided to quckly make a version that works on 1.18.2.

### CODE REVIEW

**Comment by totom121** [comment]
How can i download it ?

**Comment by JABirchall** [comment]
Just use ViaVersion https://www.curseforge.com/minecraft/mc-mods/viafabric

**Comment by The-funny-man** [comment]
can you add support for 1.8.9 by any chance?

**Comment by MrBreakNFix** [comment]
lol imagine using 1.8.9

**Comment by proman948** [comment]
Can u pls make it in 1.16.5 PLSSSSS

**Comment by MrBreakNFix** [comment]
> Can u pls make it in 1.16.5 PLSSSSS

lol no use a viafabric

**Comment by SzczurekYT** [comment]
Yep, for versions that aren't that old like 1.8.9 ViaFabric works very well.

**Comment by fivghost** [comment]
> Yep, for versions that aren't that old like 1.8.9 ViaFabric works very well.

mate, saico pvp, (the server im trying to dupe on) can detect via fabric, so that when you join the server, everything seems fine, but then as soon as you actually load into a gamemode/world it traps you in the sky  and you cant move or do anything either than just leave

**Comment by SzczurekYT** [comment]
> > Yep, for versions that aren't that old like 1.8.9 ViaFabric works very well.
> 
> mate, saico pvp, (the server im trying to dupe on) can detect via fabric, so that when you join the server, everything seems fine, but then as soon as you actually load into a gamemode/world it traps you in the sky and you cant move or do anything either than just leave

Sorry, I meant "for newer versions, that aren't as old as 1.8.9 is".

**Comment by SzczurekYT** [comment]
> > Yep, for versions that aren't that old like 1.8.9 ViaFabric works very well.
> 
> mate, saico pvp, (the server im trying to dupe on) can detect via fabric, so that when you join the server, everything seems fine, but then as soon as you actually load into a gamemode/world it traps you in the sky and you cant move or do anything either than just leave

You might want to try ViaFabricPlus, it works better.

**Pull request closed without merging**
