### PR TITLE
Fix incompatibility with mac

### PR DESCRIPTION
**Pull request by Paddyk45**
Fixes the incompatbility with mac (or atleast i hope it)

### CODE REVIEW

**Comment by Pxddyk45** [comment]
Nope it doesn't work :/

**Comment by Pxddyk45** [comment]
there we go

**Comment by MrBreakNFix** [comment]
looks good! ill ask coderx to look over it

**Comment by TBX3D** [comment]
> looks good! ill ask coderx to look over it

can you extract the .jar for me? been 2 hours can't get it

**Comment by Pxddyk45** [comment]
> > looks good! ill ask coderx to look over it
> 
> can you extract the .jar for me? been 2 hours can't get it

you mean the compiled .jar?

**Comment by kumail1009** [comment]
bro pls pls pls make ui utils also for 1.18.2

**Comment by kumail1009** [comment]
pls i need it to dupe items in server pls

**Comment by Pxddyk45** [comment]
> bro pls pls pls make ui utils also for 1.18.2

no

**Comment by kumail1009** [comment]
i can connect 1.19.3 minecraft to 1.18.2 minecraft server with the help of this file

**Comment by kumail1009** [comment]
bro pls tell this ; can i dupe in fakepixel with ui utils

**Comment by Paddyk45** [comment]
Merge conflicts :/

**Comment by Paddyk45** [comment]
Closing for now; will make another PR soon:tm:

**Comment by Paddyk45** [comment]
Oh its already fixed lol

**Pull request closed without merging**
