### PR TITLE
Updated to 1.19.3

### PR DESCRIPTION
**Pull request by stefexec**
Updated Mixins/ButtonWidgets to work with 1.19.3

### CODE REVIEW

**Review by RealSnowyBlue — APPROVED** [review]

**Comment by RealSnowyBlue** [comment]
It works and all but I'm not going to use it Ima wait for the official release. [https://github.com/Coderx-Gamer/ui-utils/pull/24](url)

**Comment by RealSnowyBlue** [comment]
The owner of this mod is mean he simply said no to a 1.19.3 version

**Comment by stefexec** [comment]
> The owner of this mod is mean he simply said no to a 1.19.3 version

lmao i might even fix the error in the button label text then

**Comment by FRAJOoOSK** [comment]
@stefexec 
Where can i download ui-utils for fabric 1.19.3 
i dont know

**Comment by MrBreakNFix** [comment]
it is 1.19.3 now lol

**Comment by Sultagurken** [comment]
> it is 1.19.3 now lol

You think you can make it to 1.19 and send it to me on discord? Sultagurken#5460

**Comment by Coderx-Gamer** [comment]
Old pr, closing.

**Pull request closed without merging**
